### ISSUE TITLE
PyPi package does not install dependencies

### ISSUE THREAD

**Issue by bwheelz36** [jonbmartin/pulpy#11]
Continuing review for https://github.com/openjournals/joss-reviews/issues/6586

I've noticed that although the package dependencies are listed in `requirements.txt`, this is not linked to the packaing of the code. As such, doing `pip install pulpy` does not install the dependencies required to run the code.

**Comment by bwheelz36** [comment]
this also applies if one does `pip install -e .` as suggested in the readme

**Comment by bwheelz36** [comment]
(this comes back to the packaging being pretty confusing. tbh, i'd recommend starting from scratch here and just using something like poetry)

**Comment by jonbmartin** [comment]
Resolved! Dependencies install correctly now with 'pip install pulpy'
